import type { ModuleMeta } from '../types'

export const MODULES: ModuleMeta[] = [
  {
    id: 1,
    slug: 'big-numbers',
    name: 'Big Numbers Comprehension',
    description: 'Identify the largest or smallest number from four 7–9 digit values.',
    icon: '🔢',
    stage: 'Stage I',
    path: '/modules/big-numbers',
  },
  {
    id: 2,
    slug: 'coordinate-system',
    name: 'Coordinate System',
    description: 'Select the correct (x, y) coordinate for a marked point on an animated grid.',
    icon: '📍',
    stage: 'Stage I',
    path: '/modules/coordinate-system',
  },
  {
    id: 3,
    slug: 'cube-folding',
    name: 'Cube Folding',
    description: 'Choose which 3D cube can be folded from the given flat net.',
    icon: '🎲',
    stage: 'Stage I',
    path: '/modules/cube-folding',
  },
  {
    id: 4,
    slug: 'divided-attention',
    name: 'Divided Attention',
    description: 'Monitor three data streams and click the one showing an outlier value.',
    icon: '📊',
    stage: 'Stage I',
    path: '/modules/divided-attention',
  },
  {
    id: 5,
    slug: 'heading-conflicts',
    name: 'Heading Conflicts',
    description: 'Identify which aircraft pair is on a converging course on the radar scope.',
    icon: '✈️',
    stage: 'Stage I',
    path: '/modules/heading-conflicts',
  },
  {
    id: 6,
    slug: 'learning-rules',
    name: 'Learning and Applying Rules',
    description: 'Apply conditional rules to determine the correct action for each scenario.',
    icon: '📋',
    stage: 'Stage I',
    path: '/modules/learning-rules',
  },
  {
    id: 7,
    slug: 'matching-figure',
    name: 'Matching Figure Test',
    description: 'Find the option that matches the reference shape (rotated, not mirrored).',
    icon: '🔷',
    stage: 'Stage I',
    path: '/modules/matching-figure',
  },
  {
    id: 8,
    slug: 'memorize-instruments',
    name: 'Memorize Instruments',
    description: 'Study the instrument panel, then answer questions from memory.',
    icon: '🎛️',
    stage: 'Stage I',
    path: '/modules/memorize-instruments',
  },
  {
    id: 9,
    slug: 'memorize-pictograms',
    name: 'Memorize Pictograms',
    description: 'Recall the sequence of aviation symbols in the correct order.',
    icon: '🛑',
    stage: 'Stage I',
    path: '/modules/memorize-pictograms',
  },
  {
    id: 10,
    slug: 'multi-attention',
    name: 'Multi Attention Test',
    description: 'Handle four simultaneous tasks: counter, shape, number sequence, and blink alert.',
    icon: '🧠',
    stage: 'Stage I',
    path: '/modules/multi-attention',
  },
  {
    id: 11,
    slug: 'planning-ability',
    name: 'Planning Ability Test',
    description: 'Pick the valid waypoint sequence that satisfies all given constraints.',
    icon: '🗺️',
    stage: 'Stage I',
    path: '/modules/planning-ability',
  },
  {
    id: 12,
    slug: 'spot-the-side',
    name: 'Spot the Side',
    description: 'Identify whether the aircraft silhouette is viewed from the left or right.',
    icon: '👁️',
    stage: 'Stage I',
    path: '/modules/spot-the-side',
  },
  {
    id: 13,
    slug: 'vigilance',
    name: 'Vigilance Test',
    description: 'Press SPACE when you spot the target character in a rapid stream.',
    icon: '⚡',
    stage: 'Stage I',
    path: '/modules/vigilance',
  },
  {
    id: 14,
    slug: 'dart',
    name: 'Dynamic Radar Test (DART)',
    description: 'Identify conflicting aircraft pairs on a live animated radar scope.',
    icon: '📡',
    stage: 'Stage II',
    path: '/modules/dart',
  },
  {
    id: 15,
    slug: 'multi-control',
    name: 'Multi Control Test',
    description: 'Simultaneously manage a radar scope and update the strip board.',
    icon: '🖥️',
    stage: 'Stage II',
    path: '/modules/multi-control',
  },
  {
    id: 16,
    slug: 'radar-control',
    name: 'Radar Control Test',
    description: 'Issue the correct instruction to resolve conflicts on a live radar.',
    icon: '🎯',
    stage: 'Stage II',
    path: '/modules/radar-control',
  },
  {
    id: 17,
    slug: 'strip-display',
    name: 'Strip Display Management',
    description: 'Update flight progress strips as events occur on the board.',
    icon: '📄',
    stage: 'Stage II',
    path: '/modules/strip-display',
  },
]

export const STAGE_I = MODULES.filter((m) => m.stage === 'Stage I')
export const STAGE_II = MODULES.filter((m) => m.stage === 'Stage II')
